platformName:Android
platVersion:7.0.1
devicesName:127.0.0.1:62001

#appPackage:com.xueqiu.android
#appActivity:.view.WelcomeActivityAlias
appPackage:io.dcloud.DCF8A1B8B  #掌上行APP
appActivity:io.dcloud.PandoraEntryActivity  #获取当前activity
unicodeKeyboard:True
aotuGrantPermissions:True




